"""task added to queue

Revision ID: 304f4e657064
Revises: bb3d17ef00af
Create Date: 2025-03-21 14:22:41.447980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304f4e657064'
down_revision: Union[str, None] = 'bb3d17ef00af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('task', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'task')
    # ### end Alembic commands ###
