"""linking metadata directly to note. adding entities

Revision ID: a3bf6e840df0
Revises: ace6417e490c
Create Date: 2025-03-21 22:43:23.456357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bf6e840df0'
down_revision: Union[str, None] = 'ace6417e490c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('entity', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('entity')
    )
    op.create_table('note_entities',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['entity'], ['entities.entity'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'entity')
    )
    op.create_table('note_keywords',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['keyword'], ['keywords.keyword'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'keyword')
    )
    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag'], ['tags.tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag')
    )
    op.create_table('snippet_entities',
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['entity'], ['entities.entity'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snippet_id', 'entity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snippet_entities')
    op.drop_table('note_tags')
    op.drop_table('note_keywords')
    op.drop_table('note_entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
