"""adding status details to queue

Revision ID: ace6417e490c
Revises: 304f4e657064
Create Date: 2025-03-21 14:57:25.081323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace6417e490c'
down_revision: Union[str, None] = '304f4e657064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('status_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'status_details')
    # ### end Alembic commands ###
